In [10]:
import numpy as np;
n1=[1,2,3,4,5,6,7]
n2=np.array(n1)
print(n2[2:7:2])
import pandas
import matplotlib

[3 5 7]


In [12]:
arr = np.array([[1,2,3,4,5],[12,13,14,15,16]])
print(arr[1,1:4])
print(arr[0:2 , 1:6])

[13 14 15]
[[ 2  3  4  5]
 [13 14 15 16]]


In [15]:
import sys 
arr = np.array([[1,2,3,4,5],[12,13,14,15,16]])
print(sys.getsizeof(arr))
print(arr.size)
print(arr.itemsize)

208
10
8


In [18]:
arr = np.empty((4,4),dtype=int)
print(arr)
print(arr.flat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
arr = np.empty((4,4),dtype=int)
print(arr)
arr.reshape(1,16)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
arr = np.array([[1,2,3,4,5],[10,2,3,4,5],[11,2,3,4,5],[17,2,3,4,5],[18,2,3,4,5]])
print(arr)
# print(arr[1:3][1:5])          not allowed 
print(arr[2:4 , 1:4])

[[ 1  2  3  4  5]
 [10  2  3  4  5]
 [11  2  3  4  5]
 [17  2  3  4  5]
 [18  2  3  4  5]]
[[11  2  3  4  5]]
[[2 3 4]
 [2 3 4]]
